 worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Список инстансов Catalog для балансировки
    upstream catalog_upstream {
        server catalog-1:8000;
        server catalog-2:8000;
    }

    server {
        listen 80;
        server_name _;

        # Маршрут /auth/* -> auth:8000
        location /auth/ {
            proxy_pass http://auth:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Маршрут /catalog/* -> upstream (catalog-1 / catalog-2)
        location /catalog/ {
            proxy_pass http://catalog_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Служебный эндпоинт для проверки
        location /health {
            return 200 '{"status":"ok","service":"nginx-gateway"}';
            add_header Content-Type application/json;
        }
    }
}